version: '3'

services:
  users:
    build:
      context: ./users
    volumes:
      - ./users:/var/www/users
    networks:
      - app_network
    expose:
      - 9000
    depends_on:
      - my-notification-service
      - mysql
      - rabbitmq

  my-notification-service:
    build:
      context: ./my-notification-service
    volumes:
      - ./my-notification-service:/var/www/my-notification-service
    networks:
      - app_network
    expose:
      - 9000

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: user-nbtask
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - users
      - my-notification-service
      - mysql
      - rabbitmq

networks:
  app_network:
